/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rotateimage;

/**
 *
 * @author mario
 */
public class RotateDemo extends javax.swing.JFrame {

    /**
     * Creates new form RotateDemo
     */
    public RotateDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        imageLoager1 = new rotateimage.imageLoager();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout imageLoager1Layout = new javax.swing.GroupLayout(imageLoager1);
        imageLoager1.setLayout(imageLoager1Layout);
        imageLoager1Layout.setHorizontalGroup(
            imageLoager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        imageLoager1Layout.setVerticalGroup(
            imageLoager1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(imageLoager1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        imageLoager1.LoadImage("C:/Users/mario/Desktop/VIII Semestre/SEMINARIOS/Progresso do Tema/images/difusi.jpg");
        imageLoager1.invalidate();
    }//GEN-LAST:event_formWindowOpened

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
       imageLoager1.RotateImage(jSlider1.getValue());
        setTitle(String.valueOf(jSlider1.getValue()*3.6));
    }//GEN-LAST:event_jSlider1StateChanged

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rotateimage.imageLoager imageLoager1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
